labworks/labwork17/LabWork17/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LabWork17.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

labworks/labwork17/LabWork17/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LabWork17.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

labworks/labwork17/LabWork17/Pages/Login.cshtml.cs
using AuthLibrary.Contexts;
using AuthLibrary.Models;
using AuthLibrary.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LabWork17.Pages
{
    public class LoginModel(CinemaUserDbContext context, AuthService authService) : PageModel
    {
        private readonly CinemaUserDbContext _context = context;
        private readonly AuthService _authService = authService;

        public IActionResult OnGet()
        {
            return Page();
        }

        public IActionResult OnGetLogout()
        {
            HttpContext.Session.Clear();
            return RedirectToPage("/Index");
        }

        [BindProperty]
        public CinemaUser CinemaUser { get; set; } = default!;

        public async Task<IActionResult> OnPostLoginAsync()
        {

            var user = await _authService.AuthUserAsync(CinemaUser.Login, CinemaUser.PasswordHash);
            var role = await _authService.GetUserRoleAsync(user.Login);

            if (user is null)
                return Page();

            HttpContext.Session.SetString("Login", user.Login);
            HttpContext.Session.SetString("Role", role.RoleName);

            return RedirectToPage("/Films/Index");
        }

        public async Task<IActionResult> OnPostGuest()
        {
            HttpContext.Session.Clear();

            HttpContext.Session.SetString("Role", "Guest");

            return RedirectToPage("/Films/Index");
        }
    }
}

labworks/labwork17/LabWork17/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LabWork17.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

labworks/labwork17/LabWork17/Pages/AuthPage.cshtml
@page
@model LabWork17.Pages.AuthPageModel
@{

}

labworks/labwork17/LabWork17/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Добро пожаловать</h1>
    <p>Лабораторная работа №17 ТРиЗБД.</p>
</div>

labworks/labwork17/LabWork17/Pages/Login.cshtml
@page
@model LabWork17.Pages.LoginModel

        @{
        ViewData["Title"] = "Вход";
        }
        
        <h1>Вход на сайт</h1>
        
    <hr />
    <div class="row">
    <div class="col-md-4">
        <form method="post" asp-page-handler="Login">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Логин</label>
                <input asp-for="CinemaUser.Login" class="form-control" />
                <span asp-validation-for="CinemaUser.Login" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Пароль</label>
                <input asp-for="CinemaUser.PasswordHash" class="form-control" type="password" />
                <span asp-validation-for="CinemaUser.PasswordHash" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Войти" class="btn btn-primary" />
            </div>
    </form>
        <form method="post" asp-page-handler="Guest">
            <div class="form-group">
                <input type="submit" value="Войти как гость" class="btn btn-primary" />
            </div>
    </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}